### PR TITLE
Simple fix for game freezing when the player touches the castle axe.

### PR DESCRIPTION
**Pull request by Geoffrey-A**

### CODE REVIEW

**Comment by JoshuaKGoldberg** [comment]
This seems like a bandaid for a deeper issue in #290. `characters` should *never* have undefined Things in it, so this (in theory) shouldn't be required.

I'm going to close this pull request and dig deeper into the issue, thanks for the fix though.

**Comment by Geoffrey-A** [comment]
My hypothesis is not that `characters` contain undefined elements. `character` is undefined because the index is out of `characters` bounds.

**Comment by JoshuaKGoldberg** [comment]
:+1: Same conclusion - that isn't a check that should be done. You are correct.

**Comment by Geoffrey-A** [comment]
Why should not it be done?
Accessing an array element with an out-of-bound index returns undefined.

**Comment by JoshuaKGoldberg** [comment]
True, but that should never happen in these loops.

The GroupHoldr arrays such as `characters` are part of the core game state; their information should always be 100% valid and a lot of functionality relies on their validity. Having a check in `maintainCharacters` for undefined members would facilitate game state continuing with that invalid aspect, which could mask bugs deeper in the code. 

Keeping `maintainCharacters` as small as possible also keeps the code cleaner (easier to use), and you never know when some little thing breaks JS optimization.

**Pull request closed without merging**
